---
title: "3_fitting_original_model_to_old_datasets"
format: html
editor: visual
---

```{r, message=FALSE, warning = FALSE}
library(tidyverse)
library(cmdstanr)

source("../../functions/import_data.R")
source("../../functions/prep_data.R")
source("../../functions/compute_summary_stats.R")
source("../../functions/plot_model.R")
source("../../functions/plot_data.R")
source("../../functions/post_functions.R")
source("../../functions/sim_foraging_data.R")

options(mc.cores = 1)

# set global ggplot theme
theme_set(ggthemes::theme_tufte())
```

# Fitting Model to Previously Collected Datasets

some text...

these are fit by scripts xxx.R and run on our cluster.

## Clarke2022qjep

## Tagu2022cog

```{r}

d <- import_data('tagu2022cog')

```

```{r, eval = FALSE}
d_list <- prep_data_for_stan(d$found, d$stim, c("spatial", "item_class"))
d_list <- add_priors_to_d_list(d_list, modelver = 1.0)

```

```{r, eval = FALSE}

iter = 100
d_list$n_trials_to_sim <- 1

mod <- cmdstan_model("../../models/multi_level/FoMo1_0.stan", 
                     cpp_options = list(stan_threads = TRUE), force_recompile = TRUE)

fit <- mod$sample(data = d_list, 
                 chains = 4, parallel_chains = 4, threads = 4,
                 refresh = 10, 
                 init = 1,
                 iter_warmup = iter, iter_sampling = iter,
                 sig_figs = 3)

fit$save_object("scratch/tagu_1_0_tmp.rds")

# pre save moment match loo
fit1_0_loo <- fit$loo(moment_match = TRUE)
saveRDS(fit1_0_loo, "scratch/tagu_1_0_loo.rds")


```

```{r, eval = FALSE}

mod1_1 <- cmdstan_model("../../models/multi_level/FoMo1_1.stan", 
                     cpp_options = list(stan_threads = TRUE), force_recompile = TRUE)

fit1_1 <- mod1_1$sample(data = d_list, 
                 chains = 4, parallel_chains = 4, threads = 4,
                 refresh = 10, 
                 init = 1,
                 iter_warmup = iter, iter_sampling = iter,
                 sig_figs = 3)

fit1_1$save_object("scratch/tagu_1_1_tmp.rds")

# pre save moment match loo
fit1_1_loo <- fit1_1$loo(moment_match = TRUE)
saveRDS(fit1_1_loo, "scratch/tagu_1_1_loo.rds")

```

### Model checking

```{r}

fit1_0 <- readRDS("scratch/tagu_1_0_tmp.rds")
fit1_1 <- readRDS("scratch/tagu_1_1_tmp.rds")

# diagnostic checks
fit1_0$diagnostic_summary()
fit1_1$diagnostic_summary()

# traceplots
bayesplot::mcmc_trace(fit1_0$draws(), pars = c("b_a[1]", "b_a[2]", "b_stick[1]", "b_stick[2]", 
                                               "rho_delta[1]", "rho_delta[2]", "rho_psi[1]", "rho_psi[2]"))

bayesplot::mcmc_trace(fit1_1$draws(), pars = c("b_a[1]", "b_a[2]", "b_stick[1]", "b_stick[2]", 
                                               "rho_delta[1]", "rho_delta[2]", "rho_psi[1]", "rho_psi[2]"))

```

### Which model fits best?

```{r}

fit1_0_loo <- readRDS("scratch/tagu_1_0_loo.rds")
fit1_1_loo <- readRDS("scratch/tagu_1_1_loo.rds")

knitr::kable(loo::loo_model_weights(list(
  "model 1.1" = fit1_1_loo,
  "model 1.0" = fit1_0_loo)))


```

This suggests that model 1.1 fits best.

### Plotting the model

```{r}

# extract post
post <- extract_post(fit1_1, d)

# plot model
# things to think about - rho delta here is squished because the scale is changed. I think this is because the prior is a bit wrong.
plot_model_fixed(post)
plot_model_random(post)

```

## Kristjansson2014plos

```{r}

d2 <- import_data('kristjansson2014plos')

```


```{r, eval = FALSE}
d2_list <- prep_data_for_stan(d2$found, d2$stim, c("spatial", "item_class"))
d2_list <- add_priors_to_d_list(d2_list, modelver = "1.0")

```

```{r, eval = FALSE}

iter = 100
d2_list$n_trials_to_sim <- 1

mod <- cmdstan_model("../../models/multi_level/FoMo1_0.stan", 
                     cpp_options = list(stan_threads = TRUE), force_recompile = TRUE)

fit <- mod$sample(data = d2_list, 
                 chains = 4, parallel_chains = 4, threads = 4,
                 refresh = 10, 
                 init = 1,
                 iter_warmup = iter, iter_sampling = iter,
                 sig_figs = 3)

fit$save_object("scratch/kristjansson_1_0_tmp.rds")

# pre save moment match loo
fit1_0_loo <- fit$loo(moment_match = TRUE)
saveRDS(fit1_0_loo, "scratch/kristjansson_1_0_loo.rds")


```